name: Build and Release

on:
  push:
    branches:
      - master

jobs:          
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare Repository
      # Fetch full git history and tags
      run: git fetch --unshallow --tags
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install packages
      run: |
        npm ci

    - name: Publish Release to Github
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npx auto shipit